### ISSUE TITLE
 Too many segments: 256 - max 255 allowed

### ISSUE THREAD

**Issue by Yoda-XY** [bailli/opus2tonie#1]
Hello and thank you so much for your script!
I always get the error with one file too many segments , what does this mean exactly?
If i encode this file alone it works, even if the file is encoded first but if the file comes in after another one, then the error occurs

THANKS!

**Comment by bailli** [comment]
This message means that you have hit an edge case which have not handled correctly. This happens when the script tries to align the Ogg pages similar to original Tonie content.

The alignment of the first file is slightly different than for the following files, therefore your observation is very plausible.

I expect copyright issues prevent you from providing the problematic file? I can try to fix the issue without it. In any case it will have to wait a bit since I lack the time currently.

Did you provide 48kHz Ogg files or other source files?

**Comment by Yoda-XY** [comment]
Hey bailli thank you for your answer! Thank you for your help! Yes i used 48khz mp3 and convert it to opus. The script convert the files very very fast and it can handle the files up to 2GB, so i can exhaust the full playtime. (limited by 2GB TonieBox ram). What teddybench could not reach.

The only problem I have is that when the toniebox goes into standby after 10 min and the played track is about 3h, the save point is not correct when switching it on. But this is probably an internal Toniebox software error, because teddy bench also does the same error and the toniebox writes the files in their own nand, which someone have told me. I hope this is still fixable

**Comment by bailli** [comment]
I tried a quick fix for the too-many-segments issue: You could give the branch [too-many-segments ](https://github.com/bailli/opus2tonie/tree/too-many-segments)a try. But this is just a wild guess...

If it not works and you can share the problematic (source) audio file **without any issues concerning its copyright** then you could either point me to place where I can get it or upload it somewhere for me. Then I will try and fix the problem.

I have no idea about the "save point" issues. Does inserting more or less chapters change something about the position from where the box actually continues in these cases? But my first guess would also be that this is a issue in the Tonie firmware and not fixable "from outside".

**Comment by Yoda-XY** [comment]
sorry the error still occurs. Yes with the copyright is really a stupid thing now to test. Can I send you the links by mail?

With the save point error. It does not matter how many chapters, it simply does not save after a certain time.

**Comment by Yoda-XY** [comment]
Here are the 2 Files, please tell me when you have downloaded the 2 files so I can remove it, thanks!!

https://drive.google.com/file/d/1Fx1RAvNoqy0n8oURfD34_dxZybfBCAyp/view?usp=drivesdk

https://drive.google.com/file/d/1HoJhKyi6UW8Vmrx0NChRh28tEsWMEuHg/view?usp=drivesdk

**Comment by bailli** [comment]
Ok. It was just a quick guess. I will try and fix it using the files you provide. Thank you.

**Comment by bailli** [comment]
It seems to work for me with your files now. You may give the version from the branch another try.

----

> With the save point error. It does not matter how many chapters, it simply does not save after a certain time.

If chapters have no impact, then it is not a problem of the audio files in my opinion.

**Comment by Yoda-XY** [comment]
Dude you are the best thank you very much ! =)
