### ISSUE TITLE
Can't generate acceptable opus files through this script

### ISSUE THREAD

**Issue by v4hn** [bailli/opus2tonie#3]
Thanks you for working on this! This is so much better and more useful than the full-blown teddy system. :medal_sports: 

Sadly I can't get it to generate files that my box accepts yet. :crying_cat_face: 
If I split an existing file and create it from the individual opus files again, it seems to work, but I can't get opusenc (0.2 (using libopus 1.3.1-fuzzing)) to produce files your tool accepts.

If I feed in an arbitrary audio file, I see the exception

> RuntimeError: Please add frame size for config value 15

If I naively add 15 [here](https://github.com/bailli/opus2tonie/blob/89940290d661b5c85229fcb6bd6a619ec5d9856f/opus2tonie.py#L106), the resulting files only turn the light of the box red.

Looking somewhat deeper into online resources I can't find a direct explanation of this `config_value` you extract from the files, so my questions at the moment are
- Should oggenc generate 15 or is there a way to force a different value? Did you miss to add a parameter to the command line and the defaults changed at some point?
- What should be the correct frame size for 15?
- What does the config_value even mean and where is it documented?

**Comment by bailli** [comment]
I am still using a slightly dated version of opusenc 
```
$ opusenc --version
opusenc opus-tools 0.1.10 (using libopus 1.1.2)
Copyright (C) 2008-2017 Xiph.Org Foundation
```

What are the parameters you invoke the script with?

> If I naively add 15 here, the resulting files only turn the light of the box red.

A quick check with the specification seems like that should be the correct thing to do. I did not add the value as my test never produced files with this type. (This might be connected with my outdated opusenc, or with the source material / selected parameters)

**Comment by v4hn** [comment]
I can only play around with this every few evenings, so please be somewhat patient with me on this. Thank you so much for responding :+1: , judging from your public github activity I expected you would not.

> What are the parameters you invoke the script with?

None at all, I rely on your script and the default parameters.

> A quick check with the specification seems like that should be the correct thing to do

Could you share a link to the relevant content? Is this value affected by the content of the audio file or the encoding flags, or both?

I just tried to go back to your versions of libopus&opus-tools, but get strange segfaults that might be due to my environment.
Do you work with a standard linux distribution I could quickly test on?

**Comment by bailli** [comment]
> I can only play around with this every few evenings, so please be somewhat patient with me on this.

No problem. Same situation on my end.

> judging from your public github activity I expected you would not.

I can see, how you would expect that :D

> Could you share a link to the relevant content? Is this value affected by the content of the audio file or the encoding flags, or both?

The relevant link is the last one from the README: https://tools.ietf.org/html/rfc6716#section-3.1
This value is the config value of the TOC byte or rather the mapping of the config value to the actual packet audio length (20 ms for "15"). So it "only" affects the calculation of the granule (basically the timestamp - I have no idea how much you know about ogg/opus). However, I would expect that the box will reject files where this part is messed up.

One thing you can do to save same time copying files to the box: Cut off the "Tonie header" and try to decode the file with opusdec. If this outputs errors it will probably be rejected.

> Do you work with a standard linux distribution I could quickly test on?

I am still on Kubuntu 18.04 :see_no_evil: I will try to test with a newer version when I have time.
What is your source material?

Just for reference: I used my script quite a few times successfully even if the readme stil states "first tests".

**Comment by v4hn** [comment]
> I have no idea how much you know about ogg/opus

Now a lot more. :grin: Thanks for your hints! :bouquet:
I got it to work and it turned out the main culprit was that my libopus was accidentally built with custom mode support and that apparently makes `opusenc` generate packets with mode 15 with default parameters.

> So it "only" affects the calculation of the granule

You missed to mention the "Hybrid" mode for config values 12-15!
I did some more testing and generated different opus encodings from the same source with 3 different `opusenc`-settings by reducing the bitrate below the standard 96.
- consisting of packets with CELT modes only
- consisting of packets with CELT and hybrid modes (I could not easily find parameters to yield only hybrid-mode packets)
- consisting of packets with SILK mode only

You can find the test files [here](http://files.v4hn.de/page_modes_tests.tar.xz).

I added the correct frame size mappings (taken from the rfc) to the script and generated tonie files for some of my figurines.
I tested them on my device and I believe the box only supports CELT altogether! The other two figurines only get the box to blink red.

I will create a pull-request to change the feedback of the script.
