### ISSUE TITLE
ValueError: Precision not allowed in integer format specifier

### ISSUE THREAD

**Issue by Yoda-XY** [bailli/opus2tonie#6]
Hello and thank u for your script again!
In the new version ive got an error.

python opus2tonie.py SOURCE
Traceback (most recent call last):
  File "opus2tonie.py", line 1052, in <module>
    args.bitrate, args.cbr, args.ffmpeg, args.opusenc)
  File "opus2tonie.py", line 658, in create_tonie_file
    format_string = "[{{:0{}d}}/{:0{}d}] {{}}".format(pad_len, len(input_files), pad_len)
ValueError: Precision not allowed in integer format specifier

**Comment by steve8x8** [comment]
@Yoda-XY Which Python version are you using?

**Comment by Yoda-XY** [comment]
Thanks i used python 2.x.x with python 3.x.x it works!
