### ISSUE TITLE
Inconsistent check for T2S?

### ISSUE THREAD

**Issue by steve8x8** [bailli/opus2tonie#7]
I was trying to add some T2S to the conversion, but failed to find `librecaptcha` for HomeBrew (which is what I'm successfully using with `opus2tonie`, Python 3.10).
The `import` therefore fails (and `requests` is not even considered any longer it seems), but addition of a `text:` line to the `.lst` file results in an error 

```
$ ./opus2tonie.py text.lst x
[01/37] text:Here it begins
Traceback (most recent call last):
  File "opus2tonie.py", line 1051, in <module>
    create_tonie_file(out_filename, files, args.no_tonie_header, args.user_timestamp,
  File "opus2tonie.py", line 669, in create_tonie_file
    handle = get_t2s_tempfile(ffmpeg, opusenc, fname[5:], bitrate, not cbr)
  File "opus2tonie.py", line 881, in get_t2s_tempfile
    t2s_base64 = get_t2s_base64_data(text)
  File "opus2tonie.py", line 865, in get_t2s_base64_data
    response = requests.post(T2S_ENDPOINT + token,
NameError: name 'requests' is not defined
```
It seems that `get_t2s_base64_data()` is called without `get_t2s_token()` having had the opportunity to fail the assertion...

Despite of this minor issue, `opus2tonie` has eventually resolved my problem of converting files back and forth on Apple Silicon, without having to go for mono or VMs. Many thanks for that :)

PS.: Is there a simple means to append tracks to an existing file?

**Comment by bailli** [comment]
As mentioned in the MR: Thanks for the hint :)

I think the current text2speech implementation does not work anymore anyway... Maybe I should just ditch it...

Fixed with [0867442](https://github.com/bailli/opus2tonie/commit/08674426f6869ab06adb0764edc9f2c0714547ec)
